package com.pipeline.video.domain;

public enum AssetType {
    KEYWORD,
    SCRIPT,
    TTS_AUDIO,
    IMAGE_BATCH,
    SCENE_IMAGE,
    GIF_CLIP,
    LONGFORM_VIDEO,
    ASSEMBLY_MANIFEST,
    IMAGE_QC_REPORT,
    QC_REPORT,
    SHORT_CLIP,
    SOURCE_VIDEO,
    TRANSCRIPT,
    SHORTS_SCENARIO,
    YOUTUBE_METADATA,
    YOUTUBE_PACKAGE_FAILURE,
    THUMBNAIL_IMAGE
}
