package com.pipeline.video.domain;

public enum JobStatus {
    DRAFT,
    KEYWORD_PENDING,
    TOPIC_EVIDENCE_REQUIRED,
    SCRIPT_PENDING,
    TTS_PENDING,
    IMAGES_PENDING,
    IMAGES_RETRY_REQUIRED,
    ASSEMBLING,
    PREVIEW_PENDING,
    SHORTS_SEGMENTS_PENDING,
    SHORTS_GENERATING,
    SHORTS_PREVIEW_PENDING,
    READY,
    PUBLISHED,
    BUDGET_BLOCKED,
    FAILED
}
