from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
GENERATED = Path(r"C:\Users\song\.codex\generated_images\019f9450-983c-72a0-b6e7-66b7df5b3bef")
OUT = ROOT / "frontend" / "public" / "thumbnail-examples"
OUT.mkdir(parents=True, exist_ok=True)
FONT = Path(r"C:\Windows\Fonts\malgunbd.ttf")


def font(size: int) -> ImageFont.FreeTypeFont:
    return ImageFont.truetype(str(FONT), size=size)


def centered(draw: ImageDraw.ImageDraw, box, value: str, size: int, fill, stroke=0, stroke_fill=(0, 0, 0)):
    left, top, right, bottom = box
    f = font(size)
    bounds = draw.multiline_textbbox((0, 0), value, font=f, spacing=4, stroke_width=stroke, align="center")
    x = left + (right - left - (bounds[2] - bounds[0])) / 2
    y = top + (bottom - top - (bounds[3] - bounds[1])) / 2
    draw.multiline_text((x, y), value, font=f, fill=fill, spacing=4, align="center", stroke_width=stroke, stroke_fill=stroke_fill)


def price_explainer() -> None:
    image = Image.open(GENERATED / "exec-8b6848ca-c1ff-41d5-b6b5-12be439a1772.png").convert("RGBA")
    draw = ImageDraw.Draw(image)
    # Speech bubble and checkout display were intentionally generated blank.
    centered(draw, (505, 45, 1015, 290), "헉! 너무 비싸", 66, (255, 207, 0), 5)
    centered(draw, (1065, 95, 1640, 195), "미국 매장 총액", 42, (37, 46, 66))
    centered(draw, (1065, 185, 1640, 365), "1,125,000원", 71, (224, 52, 47), 4)
    centered(draw, (1065, 380, 1640, 465), "같은 물건인데 왜?", 35, (35, 57, 95))
    centered(draw, (1065, 495, 1640, 585), "관세·환율·유통비", 34, (255, 129, 43), 2)
    image.save(OUT / "reference-video-price-explainer-v2.png")


def market_board() -> None:
    image = Image.open(GENERATED / "exec-dd1a1085-265b-44d9-9f9b-8cbec2282c6f.png").convert("RGBA")
    draw = ImageDraw.Draw(image)
    centered(draw, (80, 25, 880, 285), "장중 약세에서\n반등한 이유는?", 59, (255, 211, 35), 5)
    # Exact reported closing figures are composed deterministically, not generated by the image model.
    centered(draw, (180, 360, 850, 415), "코스피 종가", 34, (244, 249, 255))
    centered(draw, (180, 412, 850, 467), "8,864.24   ▲137.64 (+1.58%)", 28, (255, 99, 77), 2)
    centered(draw, (180, 498, 850, 552), "코스닥 종가", 34, (244, 249, 255))
    centered(draw, (180, 548, 850, 600), "1,031.96   ▲13.28 (+1.30%)", 28, (73, 215, 164), 2)
    centered(draw, (180, 636, 850, 690), "코스피 장중 최고", 33, (244, 249, 255))
    centered(draw, (180, 685, 850, 738), "8,872.18", 38, (255, 212, 48), 2)
    image.save(OUT / "reference-video-market-board-v2.png")


def field_alert() -> None:
    image = Image.open(GENERATED / "exec-12b2a4e6-bf38-4c88-9249-c13821413941.png").convert("RGBA")
    draw = ImageDraw.Draw(image)
    centered(draw, (880, 30, 1650, 365), "비상상태!", 86, (255, 208, 36), 6)
    draw.rounded_rectangle((250, 805, 1420, 895), radius=12, fill=(8, 12, 19, 235))
    centered(draw, (275, 812, 1395, 888), "항만이 멈추면 가격부터 흔들립니다", 37, (255, 255, 255))
    image.save(OUT / "reference-video-field-alert-v1.png")


def chalkboard_lesson() -> None:
    image = Image.open(GENERATED / "exec-728663b1-60e1-42e9-a61d-e1ba13d1a1e9.png").convert("RGBA")
    draw = ImageDraw.Draw(image)
    centered(draw, (120, 95, 350, 260), "공급망", 39, (246, 245, 225), 2)
    centered(draw, (465, 95, 700, 260), "물류비", 39, (246, 245, 225), 2)
    centered(draw, (805, 95, 1040, 260), "가격", 39, (246, 245, 225), 2)
    centered(draw, (100, 380, 395, 610), "원자재\n부족", 41, (246, 245, 225), 2)
    centered(draw, (435, 380, 730, 610), "운송\n지연", 41, (246, 245, 225), 2)
    centered(draw, (770, 380, 1060, 610), "소비자\n부담", 41, (255, 212, 48), 2)
    draw.rounded_rectangle((100, 795, 1150, 880), radius=12, fill=(8, 12, 19, 235))
    centered(draw, (125, 802, 1125, 873), "공급망 충격은 가격으로 번집니다", 36, (255, 255, 255))
    image.save(OUT / "reference-video-chalkboard-lesson-v1.png")


def improved_market_scoreboard() -> None:
    image = Image.open(GENERATED / "exec-de6facaf-c35b-4b32-a7ec-5a3c03ae25d9.png").convert("RGBA")
    draw = ImageDraw.Draw(image)
    centered(draw, (40, 30, 800, 245), "왜 장중에\n반등했나?", 67, (255, 210, 48), 6)
    centered(draw, (235, 315, 850, 365), "코스피 종가", 31, (245, 248, 255))
    centered(draw, (235, 367, 850, 420), "8,864.24   ▲1.58%", 29, (245, 248, 255), 3)
    centered(draw, (235, 455, 850, 505), "코스닥 종가", 31, (245, 248, 255))
    centered(draw, (235, 507, 850, 558), "1,031.96   ▲1.30%", 29, (245, 248, 255), 3)
    centered(draw, (235, 580, 850, 630), "코스피 장중 최고", 30, (245, 248, 255))
    centered(draw, (235, 632, 850, 695), "8,872.18", 36, (245, 248, 255), 3)
    draw.rounded_rectangle((170, 832, 1480, 920), radius=4, fill=(0, 0, 0, 238))
    centered(draw, (200, 840, 1450, 912), "숫자는 흐름과 함께 읽어야 합니다", 36, (255, 255, 255))
    image.save(OUT / "improved-market-scoreboard-v1.png")


def improved_split_comparison() -> None:
    image = Image.open(GENERATED / "exec-db3811e0-ed9f-46e3-886a-87a1abcc17d1.png").convert("RGBA")
    draw = ImageDraw.Draw(image)
    centered(draw, (80, 65, 605, 300), "공급 부족\n가격 압박", 55, (26, 26, 26), 5)
    centered(draw, (1080, 65, 1610, 300), "물류 정상\n비용 안정", 55, (26, 26, 26), 5)
    centered(draw, (660, 30, 1020, 285), "차이는\n여기서!", 56, (255, 210, 48), 5)
    draw.rounded_rectangle((210, 832, 1470, 920), radius=4, fill=(0, 0, 0, 238))
    centered(draw, (240, 840, 1440, 912), "같은 수출이라도 조건은 달라집니다", 36, (255, 255, 255))
    image.save(OUT / "improved-split-comparison-v1.png")


if __name__ == "__main__":
    price_explainer()
    market_board()
    field_alert()
    chalkboard_lesson()
    improved_market_scoreboard()
    improved_split_comparison()
